name: Deploy to Production VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            echo ">>> Puxando as últimas alterações do GitHub..."
            git pull origin main
            echo ">>> Reconstruindo e reiniciando os contêineres Docker..."
            docker-compose up -d --build
            echo ">>> Limpando imagens Docker antigas..."
            docker image prune -af
            echo ">>> Deploy concluído com sucesso!"